/**
 * Regenerates `src/client/lib/themes/omarchy-palettes.ts` from the Omarchy
 * themes installed on this machine (built-ins plus `~/.config/omarchy/themes`,
 * user themes winning). Run on a machine with Omarchy:
 *
 *   pnpm --filter @open-code-review/dashboard sync:themes
 *
 * The output is committed so the dashboard ships every palette to machines
 * that do not have Omarchy installed.
 */

import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { listOmarchyThemes } from '../src/server/services/omarchy-themes.js'

const outFile = join(dirname(fileURLToPath(import.meta.url)), '../src/client/lib/themes/omarchy-palettes.ts')

const palettes = listOmarchyThemes()
if (palettes.length === 0) {
  console.error('No Omarchy themes found (looked in /usr/share/omarchy/themes and ~/.config/omarchy/themes); leaving the file untouched.')
  process.exit(1)
}

const body = `// GENERATED by packages/dashboard/scripts/sync-omarchy-themes.ts — do not edit by hand.
// Source: Omarchy \`colors.toml\` files (built-in + user themes). Re-run \`pnpm sync:themes\` to refresh.

import type { OmarchyPalette } from '../../../shared/omarchy-theme'

export const OMARCHY_PALETTES: readonly OmarchyPalette[] = ${JSON.stringify(palettes, null, 2)}
`

writeFileSync(outFile, body)
console.log(`Wrote ${palettes.length} palettes to ${outFile}`)
